=== ulfek/MyProjects/TrainingProgramSolution/TrainingProgram/XML/workout.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/XMLSchema.xsd"
    xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="workout">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="exercises">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="exercise" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="sets" type="xs:int"/>
                    <xs:element name="reps" type="xs:int"/>
                    <xs:element name="description">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="text" type="xs:string"/>
                          <xs:element name="image" type="xs:string"/>
                          <xs:element name="video" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="muscle">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="image" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

    </xs:complexType>
  </xs:element>
</xs:schema>

=== ulfek/MyProjects/TrainingProgramSolution/TrainingProgram/XML/workout.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="Xworkout.xslt"?>

<!--Kommentar-->
<workout xmlns="http://tempuri.org/XMLSchema.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="workout.xsd">
  <name>Workoutname</name>
  <description>Workout description</description>
  <exercises>
    <exercise>
      <name>Exercise 1</name>
      <sets>6</sets>
      <reps>10</reps>
      <description>
        <text>Exercise 1 description text</text>
        <image></image>
        <video></video>
      </description>
      <muscle>
        <name>Muscle name</name>
        <image></image>
      </muscle>
    </exercise>
    <exercise>
      <name>Exercise 2</name>
      <sets>6</sets>
      <reps>10</reps>
      <description>
        <text>Exercise 2 description text</text>
        <image></image>
        <video></video>
      </description>
      <muscle>
        <name>Muscle name</name>
        <image></image>
      </muscle>
    </exercise>
    <exercise>
      <name>Exercise 3</name>
      <sets>6</sets>
      <reps>10</reps>
      <description>
        <text>Exercise 3 description text</text>
        <image></image>
        <video></video>
      </description>
      <muscle>
        <name>Muscle name</name>
        <image></image>
      </muscle>
    </exercise>
    <exercise>
      <name>Exercise 4</name>
      <sets>6</sets>
      <reps>10</reps>
      <description>
        <text>Exercise 4 description text</text>
        <image></image>
        <video></video>
      </description>
      <muscle>
        <name>Muscle name</name>
        <image></image>
      </muscle>
    </exercise>
  </exercises>
</workout>
